title: <p style="color:red;">Arash Gholami Davoodi</p>
description: <p style="color:red;">Research Fellow - Carnegie Mellon University</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
